std:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: default

diff:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.5
  res_name: default

inverse_uhei:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: default

ndvi:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: default

std_330300:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  gamma_330300: 1.0
  delta: 1.0
  tree_density: 0.01
  canopy_density: 0.3
  res_name: default