std:
  size: full
  max_cells: 100
  density_param: 1.0
  green_param: 0.0
  uhei_param: 0.0
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: higher_density

diff:
  size: full
  max_cells: 100
  density_param: 1.0
  green_param: 0.0
  uhei_param: 0.0
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.5
  res_name: higher_density

inverse_uhei:
  size: full
  max_cells: 100
  density_param: 1.0
  green_param: 0.0
  uhei_param: 0.0
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: higher_density

ndvi:
  size: full
  max_cells: 100
  density_param: 1.0
  green_param: 0.0
  uhei_param: 0.0
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: higher_density
