std:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.0
  alpha_uhei: 0.0
  res_name: no_yard

diff:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.0
  alpha_uhei: 0.5
  res_name: no_yard

inverse_uhei:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.0
  alpha_uhei: 0.0
  res_name: no_yard

ndvi:
  size: full
  max_cells: 100
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.0
  alpha_uhei: 0.0
  res_name: no_yard
