services:
  qgis-app:
    build: .
    image: TALEA/qgis-app:latest
    container_name: TALEA
    stdin_open: true     # same as `-i` for interactive mode
    tty: true            # same as `-t`
    command: bash        # start with bash, can be overridden
    env_file: .env       # <- loads variables from the .env file
