std:
  size: center
  max_cells: 20
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: default

diff:
  size: center
  max_cells: 20
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.5
  res_name: default

inverse_uhei:
  size: center
  max_cells: 20
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: default

ndvi:
  size: center
  max_cells: 20
  density_param: 0.33
  green_param: 0.33
  uhei_param: 0.34
  beta_streets: 0.2
  alpha_yards: 0.8
  alpha_uhei: 0.0
  res_name: default
